const parkingLayout = [
  { spotNumber: 40, zone: 'top-band', assignedName: 'Gustavo Rivera', placement: { x: 1.5, y: 1.0, w: 8.0, h: 12.6, orientation: 'vertical' } },
  { spotNumber: 17, zone: 'top-band', assignedName: 'Soly German', placement: { x: 10.2, y: 1.0, w: 7.0, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 16, zone: 'top-band', assignedName: 'Manuel Solis', placement: { x: 18.4, y: 1.0, w: 7.0, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 15, zone: 'top-band', assignedName: 'Juan Corona', placement: { x: 26.6, y: 1.0, w: 7.0, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 14, zone: 'top-band', assignedName: 'Jorge Flores', placement: { x: 34.8, y: 1.0, w: 7.0, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 13, zone: 'top-band', assignedName: 'Luis Solis', placement: { x: 43.2, y: 1.0, w: 7.8, h: 11.8, orientation: 'vertical' } },
  { spotNumber: 12, zone: 'top-band', assignedName: 'Angelica Enriquez', placement: { x: 54.8, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 11, zone: 'top-band', assignedName: 'Ana Carter', placement: { x: 62.2, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 10, zone: 'top-band', assignedName: 'Felix Zapata', placement: { x: 69.6, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 9, zone: 'top-band', assignedName: 'Margarita Guadarrama', placement: { x: 77.0, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 8, zone: 'top-band', assignedName: 'Maru Ortiz', placement: { x: 84.4, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 7, zone: 'top-band', assignedName: 'Rosa Desares', placement: { x: 91.8, y: 1.0, w: 6.3, h: 10.2, orientation: 'vertical' } },
  { spotNumber: 41, zone: 'upper-left', assignedName: 'Bruno Barquera', placement: { x: 1.4, y: 12.8, w: 11.5, h: 5.0, orientation: 'horizontal' } },
  { spotNumber: 42, zone: 'upper-left', assignedName: 'Rogelio Vazquez', placement: { x: 15.5, y: 12.8, w: 14.5, h: 5.0, orientation: 'horizontal' } },
  { spotNumber: 39, zone: 'upper-right', assignedName: 'Pepe Bernal', placement: { x: 60.2, y: 12.8, w: 9.0, h: 5.0, orientation: 'horizontal' } },
  { spotNumber: 36, zone: 'upper-right', assignedName: 'Carolina Reyes', placement: { x: 71.3, y: 12.8, w: 8.0, h: 5.0, orientation: 'horizontal' } },
  { spotNumber: 35, zone: 'upper-right', assignedName: 'Andres Alva', placement: { x: 82.2, y: 12.8, w: 11.5, h: 5.0, orientation: 'horizontal' } },
  { spotNumber: 18, zone: 'left-column', assignedName: 'Lorena Arochi', placement: { x: 1.5, y: 24.0, w: 10.0, h: 14.0, orientation: 'vertical' } },
  { spotNumber: 19, zone: 'left-column', assignedName: 'Armando Rodriguez', placement: { x: 1.5, y: 40.5, w: 10.0, h: 14.0, orientation: 'vertical' } },
  { spotNumber: 20, zone: 'left-column', assignedName: 'Sonia Becerril', placement: { x: 1.5, y: 57.0, w: 10.0, h: 14.0, orientation: 'vertical' } },
  { spotNumber: 33, zone: 'left-inner', assignedName: 'Karla Albiter', placement: { x: 26.5, y: 29.5, w: 7.8, h: 18.0, orientation: 'vertical' } },
  { spotNumber: 32, zone: 'left-inner', assignedName: 'Angel Magana', placement: { x: 26.5, y: 48.7, w: 7.8, h: 18.0, orientation: 'vertical' } },
  { spotNumber: 31, zone: 'left-inner', assignedName: 'Alonso Gil', placement: { x: 26.5, y: 67.9, w: 7.8, h: 18.0, orientation: 'vertical' } },
  { spotNumber: 30, zone: 'center-left', assignedName: 'Liliana Sanchez', placement: { x: 35.6, y: 22.8, w: 10.6, h: 10.0, orientation: 'vertical' } },
  { spotNumber: 29, zone: 'center-left', assignedName: 'Erica Macedo', placement: { x: 35.6, y: 34.3, w: 10.6, h: 10.0, orientation: 'vertical' } },
  { spotNumber: 28, zone: 'center-left', assignedName: 'Berenice Padua', placement: { x: 35.6, y: 45.8, w: 10.6, h: 10.0, orientation: 'vertical' } },
  { spotNumber: 27, zone: 'center-left', assignedName: 'Diana Chigora', placement: { x: 35.6, y: 57.3, w: 10.6, h: 10.0, orientation: 'vertical' } },
  { spotNumber: 26, zone: 'center-left', assignedName: 'Carlos Garcia', placement: { x: 35.6, y: 68.8, w: 10.6, h: 10.0, orientation: 'vertical' } },
  { spotNumber: 25, zone: 'center-right', assignedName: 'Sandra Garcia', placement: { x: 51.5, y: 35.0, w: 11.4, h: 9.6, orientation: 'vertical' } },
  { spotNumber: 24, zone: 'center-right', assignedName: 'Marco Gutierrez', placement: { x: 51.5, y: 46.6, w: 11.4, h: 9.6, orientation: 'vertical' } },
  { spotNumber: 23, zone: 'center-right', assignedName: 'Tania Clemente', placement: { x: 51.5, y: 58.2, w: 11.4, h: 9.6, orientation: 'vertical' } },
  { spotNumber: 22, zone: 'center-right', assignedName: 'Clementina Rocha', placement: { x: 51.5, y: 69.8, w: 11.4, h: 9.6, orientation: 'vertical' } },
  { spotNumber: 21, zone: 'center-right', assignedName: 'Gabriela Saldana', placement: { x: 51.5, y: 81.4, w: 11.4, h: 9.6, orientation: 'vertical' } },
  { spotNumber: 37, zone: 'lower-right', assignedName: 'Israel Paez', placement: { x: 66.6, y: 76.0, w: 7.2, h: 13.0, orientation: 'vertical' } },
  { spotNumber: 38, zone: 'lower-right', assignedName: 'Javier Castro', placement: { x: 78.2, y: 76.0, w: 7.2, h: 13.0, orientation: 'vertical' } },
  { spotNumber: 34, zone: 'right-column', assignedName: 'Dalila San Juan', placement: { x: 90.8, y: 17.5, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 6, zone: 'right-column', assignedName: 'Ivan Gonzalez', placement: { x: 90.8, y: 28.7, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 5, zone: 'right-column', assignedName: 'Carolina Rodriguez', placement: { x: 90.8, y: 39.9, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 4, zone: 'right-column', assignedName: 'Guadalupe Garduno', placement: { x: 90.8, y: 51.1, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 3, zone: 'right-column', assignedName: 'Ana Luna', placement: { x: 90.8, y: 62.3, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 2, zone: 'right-column', assignedName: 'Iratcy Velazquez', placement: { x: 90.8, y: 73.5, w: 8.2, h: 9.2, orientation: 'vertical' } },
  { spotNumber: 1, zone: 'right-column', assignedName: 'Giovani Cruz', placement: { x: 90.8, y: 84.7, w: 8.2, h: 9.2, orientation: 'vertical' } }
];

module.exports = parkingLayout;